---
# tasks file or softwareupdate-hardening

## Activate GPGcheck globally
## Rationale: It is important to ensure that an RPM's package signature is always checked prior to installation to ensure that the software is obtained from a trusted source.
- name: CIS Hardening | Ensuregpgcheck is globally activated
  ansible.builtin.command: grep ^gpgcheck /etc/yum.conf
  register: gpgcheckglobal
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- debug: var=gpgcheckglobal.stdout_lines

## The following task is not mandatory. I had included this task as a part of the process for new VMs in case if they are not updated

- name: Updating Packages -- CentOS or RedHat
  ansible.builtin.yum:
    name: "*"
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterpise Linux'


