---
- name: Verify and Install SELinux
  ansible.builtin.yum:
    name: libselinux
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: CIS Hardening | EnsureSELinux or Apparmor is installed
  ansible.builtin.apt:
    name: apparmor
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: CIS Hardening | EnsureSELinux is not disabled in the bootloader configuration
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  with_items:
    - { regexp: 'selinux=0', replace: '' }
    - { regexp: 'enforcing=0', replace: '' }

- name: CIS Hardening | EnsureAppArmor is not disabled in the bootloader configuration
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: 'apparmor=0'
    replace: ' '
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update Grub configuration
  ansible.builtin.command: update-grub
  args:
    executable: /bin/bash
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#  - name: CIS Hardening | EnsureSELinux policy is configured
#    command: sestatus | grep "Loaded"
#    register: selinuxstatus
#  - debug:
#      msg: "{{ selinuxstatus.stdout }}"

- name: CIS Hardening | EnsureSELinux state is enforcing
  ansible.builtin.shell: sestatus
  register: sestatus
  args:
     executable: /bin/bash
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- debug: var=sestatus.stdout_lines

- name: CIS Hardening | EnsureAppArmour profiles are enforcing
  ansible.builtin.command: apparmor_status
  register: apparmour
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- debug: var=apparmour.stdout_lines

#  - name: CIS Hardening | Ensureno unconfined daemons exist
#    command: |
#      ps -eZ | egrep "initrc" | egrep -vw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
#    args:
#       executable: /bin/bash
#    register: unconfined
#    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#  - debug: var=unconfined.stdout_lines

- name: CIS Hardening | EnsureSETroubleshoot is not installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "mcstrans"
    - "setroubleshoot"
    - "ypbind"
    - "telnet"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
