---
# tasks file for fileintegrity-checking
- name: Check AIDE is installed and present - CentOS or Red Hat Distribution only
  ansible.builtin.yum:
    name: aide
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## The following commented lines should be implemented. but currently experiencing some issues. Need to troubleshoot.

- block:
  - name: Check if already an AIDE installation exists on CentOS hosts
    ansible.builtin.stat: path=/var/lib/aide/aideinstallation.log
    register: ccentos
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Verify if the path exists
    ansible.builtin.command: echo "An AIDE installation already exists, Progressing to next task"
    when:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      - ccentos.stat.exists == true
  - name: Configure AIDE
    shell: |
      aide --init >> /var/lib/aide/aideinstallation.log
      mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
    args:
      executable: /bin/bash
    when:
      - ansible_distribution == 'Centos' or ansible_distribution == 'Red Hat Enterprise Linux'
      - ccentos.stat.exists == false

- name: CIS Hardening | Ensure filesystem integrity is regularly checked
  ansible.builtin.cron:
    name: aide_check
    minute: "0"
    hour: "5"
    user: root
    job: /usr/sbin/aide --check
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
