---
# tasks file for filesystem-hardeninig

- name: CIS Hardening | Disable Cramfs filesystem
  ansible.builtin.command: lsmod | grep cramfs
  register: cramfs
  failed_when: cramfs.rc != 1 and cramfs.rc != 0
- ansible.builtin.debug: var=cramfs.stdout_lines

- name: CIS Hardening | Disable freevxfs
  ansible.builtin.command: lsmod | grep freevxfs
  register: freevxfs
  failed_when: freevxfs.rc != 1 and freevxfs.rc != 0
- ansible.builtin.debug: var=freevxfs.stdout_lines

- name: CIS Hardening | Ensure jffs2 file system is disabled
  ansible.builtin.command: lsmod | grep jffs2
  register: jffs2fs
  failed_when: jffs2fs.rc != 1 and jffs2fs.rc != 0
- ansible.builtin.debug: var=jffs2fs.stdout_lines 
 
- name: CIS Hardening | Ensure squashfs filesystem is disabled
  ansible.builtin.command: lsmod | grep squashfs
  register: squashfs
  failed_when: squashfs.rc != 1 and squashfs.rc != 0
- ansible.builtin.debug: var=squashfs.stdout_lines

- name: CIS Hardening | Ensure hfs filesystem is disabled
  ansible.builtin.command: lsmod | grep hfs
  register: hfsfs
  failed_when: hfsfs.rc != 1 and hfsfs.rc != 0
- ansible.builtin.debug: var=hfsfs.stdout_lines

- name: CIS Hardening | Ensure hfsplus filesystem is disabled
  ansible.builtin.command: lsmod | grep hfsplus
  register: hfsplus
  failed_when: hfsplus.rc != 1 and hfsplus.rc != 0
- ansible.builtin.debug: var=hfsplus.stdout_lines

- name: CIS Hardening | Ensure udf filesystem is disabled
  ansible.builtin.command: lsmod | grep udf
  register: udffs
  failed_when: udffs.rc != 1 and udffs.rc != 0
- ansible.builtin.debug: var=udffs.stdout_lines

- name: CIS Hardening | Ensure sticky bit is set on all world writable directories
  ansible.builtin.command: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
  register: stickybit
  failed_when: stickybit.rc != 1 and stickybit.rc != 0
- ansible.builtin.debug: var=stickybit.stdout_lines

#  - name: Check if Autofs is running 
#    stat: yum=autofs state=absent
#    register: autois_installed
#    failed_when: autois_installed.exists
#  - name: Stop if Autofs is running
#    systemd: name={{autofs}} state={{stopped}} enabled={{no}}
#    failed_when: not autois_installed.stat.exists

- name: Disable USB Storage
  ansible.builtin.command: lsmod | grep usb-storage
  register: disableusb
  failed_when: disableusb.rc != 1 and disableusb.rc != 0
- ansible.builtin.debug: var=disableusb.stdout_lines
